### PR TITLE
Add option to only change the text color without providing any border or background.

### PR DESCRIPTION
**Pull request by CleanCut**
I would like to only change the text color, and not have any border or background. Would this do the trick? (I'm not sure how to test this out)

@zerefdev Apologies for the messed up PR in https://github.com/CleanCut/todo-highlighter/pull/1 -- That was an attempt to use the VS Code Pull Request plugin to create a pull request within VS Code. Not a great experience! 🙁  I think I'll stick with the web UI.

### CODE REVIEW

**Comment by CleanCut** [comment]
By the way, how did you notice https://github.com/CleanCut/todo-highlighter/pull/1 in the first place? Looking at it, I would not have expected you to even have received a notification about it.

**Comment by zerefdev** [comment]
@CleanCut I saw the fork notification on my feed, out of curiosity I clicked on the *fork link* and I noticed there was a pending PR.

**Comment by CleanCut** [comment]
That's a lot of luck that you saw it!

**Comment by CleanCut** [comment]
I saw that you made the 1.0.1 release. I updated in VS Code and it seems to be working great! Thanks!

**Pull request merged**
